//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MERCY_Ctx : DbContext
    {
        public MERCY_Ctx()
            : base("name=MERCY_Ctx")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Loading_Plan> Loading_Plan { get; set; }
        public virtual DbSet<Loading_Plan_Detail_Barge> Loading_Plan_Detail_Barge { get; set; }
        public virtual DbSet<Loading_Plan_Detail_Barge_Blending_Formula> Loading_Plan_Detail_Barge_Blending_Formula { get; set; }
        public virtual DbSet<Loading_Plan_Detail_Barge_Quality> Loading_Plan_Detail_Barge_Quality { get; set; }
        public virtual DbSet<Loading_Request> Loading_Request { get; set; }
        public virtual DbSet<Loading_Request_Loading_Plan> Loading_Request_Loading_Plan { get; set; }
        public virtual DbSet<Loading_Request_Loading_Plan_Detail_Barge> Loading_Request_Loading_Plan_Detail_Barge { get; set; }
        public virtual DbSet<Loading_Request_Loading_Plan_Detail_Barge_Blending_Formula> Loading_Request_Loading_Plan_Detail_Barge_Blending_Formula { get; set; }
        public virtual DbSet<Loading_Request_Loading_Plan_Detail_Barge_Quality> Loading_Request_Loading_Plan_Detail_Barge_Quality { get; set; }
        public virtual DbSet<AnalysisRequest> AnalysisRequests { get; set; }
        public virtual DbSet<AnalysisRequest_Detail> AnalysisRequest_Detail { get; set; }
        public virtual DbSet<AnalysisRequest_History> AnalysisRequest_History { get; set; }
        public virtual DbSet<AnalysisRequest_Result> AnalysisRequest_Result { get; set; }
        public virtual DbSet<Apii> Apiis { get; set; }
        public virtual DbSet<Barge_Survey_Condition> Barge_Survey_Condition { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<Consumable> Consumables { get; set; }
        public virtual DbSet<Consumable_History> Consumable_History { get; set; }
        public virtual DbSet<DirectShipment> DirectShipments { get; set; }
        public virtual DbSet<Discussion> Discussions { get; set; }
        public virtual DbSet<Draft_Survey> Draft_Survey { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Fuel_Rob> Fuel_Rob { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<HaulingRequest> HaulingRequests { get; set; }
        public virtual DbSet<HaulingRequest_Detail> HaulingRequest_Detail { get; set; }
        public virtual DbSet<HaulingRequest_Detail_PortionBlending> HaulingRequest_Detail_PortionBlending { get; set; }
        public virtual DbSet<HaulingRequest_Detail_PortionBlending_Details> HaulingRequest_Detail_PortionBlending_Details { get; set; }
        public virtual DbSet<HaulingRequest_Detail_ROMTransfer> HaulingRequest_Detail_ROMTransfer { get; set; }
        public virtual DbSet<Hopper> Hoppers { get; set; }
        public virtual DbSet<Instrument> Instruments { get; set; }
        public virtual DbSet<LabMaintenance> LabMaintenances { get; set; }
        public virtual DbSet<LabMaintenance_Complete> LabMaintenance_Complete { get; set; }
        public virtual DbSet<LabMaintenance_History> LabMaintenance_History { get; set; }
        public virtual DbSet<Loading_Actual> Loading_Actual { get; set; }
        public virtual DbSet<Loading_Actual_Attachments> Loading_Actual_Attachments { get; set; }
        public virtual DbSet<Loading_Actual_Barge_Survey_Condition> Loading_Actual_Barge_Survey_Condition { get; set; }
        public virtual DbSet<Loading_Actual_Cargo_Loaded> Loading_Actual_Cargo_Loaded { get; set; }
        public virtual DbSet<Loading_Actual_Coal_Temperature> Loading_Actual_Coal_Temperature { get; set; }
        public virtual DbSet<Loading_Actual_Draft_Survey> Loading_Actual_Draft_Survey { get; set; }
        public virtual DbSet<Loading_Actual_Fuel_Consumption> Loading_Actual_Fuel_Consumption { get; set; }
        public virtual DbSet<MaintenanceActivity> MaintenanceActivities { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Port_Loading> Port_Loading { get; set; }
        public virtual DbSet<PortionBlending> PortionBlendings { get; set; }
        public virtual DbSet<PortionBlending_Details> PortionBlending_Details { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ReadRequest> ReadRequests { get; set; }
        public virtual DbSet<Reminder_History_Lab_Consumable> Reminder_History_Lab_Consumable { get; set; }
        public virtual DbSet<Reminder_History_Lab_Maintenance> Reminder_History_Lab_Maintenance { get; set; }
        public virtual DbSet<ROM> ROMs { get; set; }
        public virtual DbSet<ROMTransfer> ROMTransfers { get; set; }
        public virtual DbSet<SamplingRequest> SamplingRequests { get; set; }
        public virtual DbSet<SamplingRequest_History> SamplingRequest_History { get; set; }
        public virtual DbSet<SamplingRequest_Lab> SamplingRequest_Lab { get; set; }
        public virtual DbSet<SamplingRequest_ROM> SamplingRequest_ROM { get; set; }
        public virtual DbSet<SamplingRequest_SEAM> SamplingRequest_SEAM { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<TEMPORARY_Barge_Line_Up> TEMPORARY_Barge_Line_Up { get; set; }
        public virtual DbSet<TEMPORARY_BARGE_LOADING> TEMPORARY_BARGE_LOADING { get; set; }
        public virtual DbSet<TEMPORARY_BARGE_LOADING_COA> TEMPORARY_BARGE_LOADING_COA { get; set; }
        public virtual DbSet<TEMPORARY_BARGE_LOADING_Header> TEMPORARY_BARGE_LOADING_Header { get; set; }
        public virtual DbSet<TEMPORARY_Barge_Quality_Plan> TEMPORARY_Barge_Quality_Plan { get; set; }
        public virtual DbSet<TEMPORARY_Barge_Quality_Plan_Header> TEMPORARY_Barge_Quality_Plan_Header { get; set; }
        public virtual DbSet<TEMPORARY_CRUSHING_PLANT> TEMPORARY_CRUSHING_PLANT { get; set; }
        public virtual DbSet<TEMPORARY_CRUSHING_PLANT_Header> TEMPORARY_CRUSHING_PLANT_Header { get; set; }
        public virtual DbSet<TEMPORARY_File> TEMPORARY_File { get; set; }
        public virtual DbSet<TEMPORARY_Geology_Explorasi> TEMPORARY_Geology_Explorasi { get; set; }
        public virtual DbSet<TEMPORARY_Geology_Explorasi_Header> TEMPORARY_Geology_Explorasi_Header { get; set; }
        public virtual DbSet<TEMPORARY_Geology_Pit_Monitoring> TEMPORARY_Geology_Pit_Monitoring { get; set; }
        public virtual DbSet<TEMPORARY_Geology_Pit_Monitoring_Header> TEMPORARY_Geology_Pit_Monitoring_Header { get; set; }
        public virtual DbSet<TEMPORARY_HAC> TEMPORARY_HAC { get; set; }
        public virtual DbSet<TEMPORARY_HAC_Header> TEMPORARY_HAC_Header { get; set; }
        public virtual DbSet<TEMPORARY_SampleDetail> TEMPORARY_SampleDetail { get; set; }
        public virtual DbSet<TEMPORARY_Sampling_ROM> TEMPORARY_Sampling_ROM { get; set; }
        public virtual DbSet<TEMPORARY_Sampling_ROM_Header> TEMPORARY_Sampling_ROM_Header { get; set; }
        public virtual DbSet<TEMPORARY_VLU> TEMPORARY_VLU { get; set; }
        public virtual DbSet<Tunnel_Actual> Tunnel_Actual { get; set; }
        public virtual DbSet<Tunnel_Actual_History> Tunnel_Actual_History { get; set; }
        public virtual DbSet<UnitMeasurement> UnitMeasurements { get; set; }
        public virtual DbSet<UPLOAD_Barge_Line_Up> UPLOAD_Barge_Line_Up { get; set; }
        public virtual DbSet<UPLOAD_BARGE_LOADING> UPLOAD_BARGE_LOADING { get; set; }
        public virtual DbSet<UPLOAD_BARGE_LOADING_COA> UPLOAD_BARGE_LOADING_COA { get; set; }
        public virtual DbSet<UPLOAD_BARGE_LOADING_Header> UPLOAD_BARGE_LOADING_Header { get; set; }
        public virtual DbSet<UPLOAD_Barge_Quality_Plan> UPLOAD_Barge_Quality_Plan { get; set; }
        public virtual DbSet<UPLOAD_Barge_Quality_Plan_Header> UPLOAD_Barge_Quality_Plan_Header { get; set; }
        public virtual DbSet<UPLOAD_CRUSHING_PLANT> UPLOAD_CRUSHING_PLANT { get; set; }
        public virtual DbSet<UPLOAD_Geology_Explorasi> UPLOAD_Geology_Explorasi { get; set; }
        public virtual DbSet<UPLOAD_Geology_Explorasi_Header> UPLOAD_Geology_Explorasi_Header { get; set; }
        public virtual DbSet<UPLOAD_Geology_Pit_Monitoring> UPLOAD_Geology_Pit_Monitoring { get; set; }
        public virtual DbSet<UPLOAD_Geology_Pit_Monitoring_Header> UPLOAD_Geology_Pit_Monitoring_Header { get; set; }
        public virtual DbSet<UPLOAD_HAC> UPLOAD_HAC { get; set; }
        public virtual DbSet<UPLOAD_HAC_Header> UPLOAD_HAC_Header { get; set; }
        public virtual DbSet<UPLOAD_LECO_CV> UPLOAD_LECO_CV { get; set; }
        public virtual DbSet<UPLOAD_LECO_TGA> UPLOAD_LECO_TGA { get; set; }
        public virtual DbSet<UPLOAD_LECO_TS> UPLOAD_LECO_TS { get; set; }
        public virtual DbSet<UPLOAD_Sampling_ROM> UPLOAD_Sampling_ROM { get; set; }
        public virtual DbSet<UPLOAD_Sampling_ROM_Header> UPLOAD_Sampling_ROM_Header { get; set; }
        public virtual DbSet<UPLOAD_VLU> UPLOAD_VLU { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Activity> User_Activity { get; set; }
        public virtual DbSet<UserCompany> UserCompanies { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserSite> UserSites { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<RefType> RefTypes { get; set; }
        public virtual DbSet<Tunnel> Tunnels { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<AnalysisResult> AnalysisResults { get; set; }
        public virtual DbSet<CompanyScheme> CompanySchemes { get; set; }
        public virtual DbSet<Scheme> Schemes { get; set; }
        public virtual DbSet<AnalysisResultHistory> AnalysisResultHistories { get; set; }
        public virtual DbSet<CompanyRefType> CompanyRefTypes { get; set; }
        public virtual DbSet<SampleDetailGeneral> SampleDetailGenerals { get; set; }
        public virtual DbSet<SampleDetailLoading> SampleDetailLoadings { get; set; }
        public virtual DbSet<SampleScheme> SampleSchemes { get; set; }
        public virtual DbSet<TunnelHistory> TunnelHistories { get; set; }
        public virtual DbSet<CompanyProject> CompanyProjects { get; set; }
        public virtual DbSet<AnalysisJob> AnalysisJobs { get; set; }
        public virtual DbSet<LoadingReport> LoadingReports { get; set; }
        public virtual DbSet<LoadingReportHeader> LoadingReportHeaders { get; set; }
        public virtual DbSet<AnalysisRequestSample> AnalysisRequestSamples { get; set; }
        public virtual DbSet<CompanyClientProjectScheme> CompanyClientProjectSchemes { get; set; }
        public virtual DbSet<UPLOAD_CRUSHING_PLANT_Header> UPLOAD_CRUSHING_PLANT_Header { get; set; }
        public virtual DbSet<BargeLineUpMapping> BargeLineUpMappings { get; set; }
        public virtual DbSet<CoalInventoryDetail> CoalInventoryDetails { get; set; }
        public virtual DbSet<ROMLocation> ROMLocations { get; set; }
        public virtual DbSet<ROMLocationDetail> ROMLocationDetails { get; set; }
        public virtual DbSet<CoalInventoryAttachment> CoalInventoryAttachments { get; set; }
        public virtual DbSet<Sample> Samples { get; set; }
        public virtual DbSet<CoalInventory> CoalInventories { get; set; }
        public virtual DbSet<CompanyShift> CompanyShifts { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<SampleDetailAMD> SampleDetailAMDs { get; set; }
        public virtual DbSet<UPLOAD_Geology_AMD> UPLOAD_Geology_AMD { get; set; }
        public virtual DbSet<UPLOAD_Geology_AMD_Header> UPLOAD_Geology_AMD_Header { get; set; }
    }
}
