//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisRequest_Detail
    {
        public long RecordId { get; set; }
        public long AnalysisRequest { get; set; }
        public string SampleID { get; set; }
        public decimal From { get; set; }
        public decimal To { get; set; }
        public string Thick { get; set; }
        public string SampleType { get; set; }
        public string SEAM { get; set; }
        public string LabId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public int DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool Verification { get; set; }
        public string Verification_Comment { get; set; }
        public bool ReTest { get; set; }
        public string Company { get; set; }
        public string CreatedOn_Date_Only { get; set; }
        public int CreatedOn_Year_Only { get; set; }
        public string RockType { get; set; }
        public int Length { get; set; }
        public decimal MPA { get; set; }
        public decimal TS { get; set; }
        public decimal PH { get; set; }
        public decimal NAPP { get; set; }
        public decimal ANC { get; set; }
        public decimal NAG { get; set; }
    
        public virtual AnalysisRequest AnalysisRequest1 { get; set; }
    }
}
