//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barge_Survey_Condition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Barge_Survey_Condition()
        {
            this.Loading_Actual_Barge_Survey_Condition = new HashSet<Loading_Actual_Barge_Survey_Condition>();
        }
    
        public int RecordId { get; set; }
        public string Barge_Survey_Condition_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loading_Actual_Barge_Survey_Condition> Loading_Actual_Barge_Survey_Condition { get; set; }
    }
}
