//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BargeLineUpMapping
    {
        public int Id { get; set; }
        public string DataRequired { get; set; }
        public string TemplateColumn { get; set; }
        public string Sheet { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string DataKey { get; set; }
    }
}
