//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoalInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoalInventory()
        {
            this.CoalInventoryAttachments = new HashSet<CoalInventoryAttachment>();
            this.CoalInventoryDetails = new HashSet<CoalInventoryDetail>();
        }
    
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public int ROMLocationId { get; set; }
        public System.DateTime Period { get; set; }
        public System.DateTime SurveyDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<decimal> Tonnage { get; set; }
        public string Status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ROMLocation ROMLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoalInventoryAttachment> CoalInventoryAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoalInventoryDetail> CoalInventoryDetails { get; set; }
    }
}
