//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectShipment
    {
        public int RecordId { get; set; }
        public string BuyerName { get; set; }
        public string Destination { get; set; }
        public decimal CV { get; set; }
        public decimal TS { get; set; }
        public decimal ASH { get; set; }
        public decimal IM { get; set; }
        public decimal TM { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public bool IsActive { get; set; }
    }
}
