//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion
    {
        public int RecordId { get; set; }
        public string Page { get; set; }
        public long ReferenceId { get; set; }
        public string Typeof { get; set; }
        public string Remark { get; set; }
        public string Attached { get; set; }
        public string Attached2 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
