//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaulingRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HaulingRequest()
        {
            this.HaulingRequest_Detail = new HashSet<HaulingRequest_Detail>();
            this.HaulingRequest_Detail_PortionBlending_Details = new HashSet<HaulingRequest_Detail_PortionBlending_Details>();
            this.HaulingRequest_Detail_PortionBlending = new HashSet<HaulingRequest_Detail_PortionBlending>();
            this.HaulingRequest_Detail_ROMTransfer = new HashSet<HaulingRequest_Detail_ROMTransfer>();
        }
    
        public long RecordId { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public int DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HaulingRequest_Detail> HaulingRequest_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HaulingRequest_Detail_PortionBlending_Details> HaulingRequest_Detail_PortionBlending_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HaulingRequest_Detail_PortionBlending> HaulingRequest_Detail_PortionBlending { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HaulingRequest_Detail_ROMTransfer> HaulingRequest_Detail_ROMTransfer { get; set; }
    }
}
