//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaulingRequest_Detail
    {
        public long RecordId { get; set; }
        public long HaulingRequest { get; set; }
        public string DataType { get; set; }
        public long DataId { get; set; }
    
        public virtual HaulingRequest HaulingRequest1 { get; set; }
    }
}
