//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabMaintenance
    {
        public long RecordId { get; set; }
        public int Category { get; set; }
        public int Instrument { get; set; }
        public string InstrumentCode { get; set; }
        public string Description { get; set; }
        public int AssignedTo { get; set; }
        public string Remark { get; set; }
        public System.DateTime NextSchedule { get; set; }
        public string RepeatEvery { get; set; }
        public int RepeatCount { get; set; }
        public string NotesFile { get; set; }
        public string NotesFile2 { get; set; }
        public string RunWhat { get; set; }
        public string RunWhat2 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public bool IsActive { get; set; }
        public string CompanyCode { get; set; }
        public int SiteId { get; set; }
    
        public virtual Instrument Instrument1 { get; set; }
        public virtual MaintenanceActivity MaintenanceActivity { get; set; }
        public virtual Site Site { get; set; }
    }
}
