//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingReportHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoadingReportHeader()
        {
            this.LoadingReports = new HashSet<LoadingReport>();
        }
    
        public int Id { get; set; }
        public string ReportNumber { get; set; }
        public string ReportTo { get; set; }
        public System.DateTime ReportedDate { get; set; }
        public string StandardMethod { get; set; }
        public string CompanyCode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedOnDate { get; set; }
        public Nullable<int> CreatedOnYear { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadingReport> LoadingReports { get; set; }
    }
}
