//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loading_Plan_Detail_Barge_Blending_Formula
    {
        public long RecordId { get; set; }
        public long Loading_Plan_Id { get; set; }
        public long Detail_Barge_Id { get; set; }
        public string Tunnel { get; set; }
        public int Stock { get; set; }
        public decimal CV { get; set; }
        public decimal TS { get; set; }
        public decimal ASH { get; set; }
        public decimal IM { get; set; }
        public decimal TM { get; set; }
        public int Portion { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int TunnelID { get; set; }
    }
}
