//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingReport
    {
        public int Id { get; set; }
        public int HeaderId { get; set; }
        public string VesselName { get; set; }
        public string LoadingNumber { get; set; }
        public int LotNumber { get; set; }
        public System.DateTime SamplingDateStart { get; set; }
        public System.DateTime SamplingDateEnd { get; set; }
        public System.DateTime AnalysisDateStart { get; set; }
        public System.DateTime AnalysisDateEnd { get; set; }
        public decimal TM { get; set; }
        public decimal IM { get; set; }
        public decimal ASH { get; set; }
        public decimal VM { get; set; }
        public decimal FC { get; set; }
        public decimal TS { get; set; }
        public decimal CVAdb { get; set; }
        public decimal CVArb { get; set; }
        public decimal CVDb { get; set; }
        public decimal CVDaf { get; set; }
        public decimal Tonnage { get; set; }
        public decimal Size50 { get; set; }
        public decimal Size502 { get; set; }
        public decimal Size2 { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string CreatedOnDate { get; set; }
        public Nullable<int> CreatedOnYear { get; set; }
    
        public virtual LoadingReportHeader LoadingReportHeader { get; set; }
    }
}
