//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loading_Plan_Detail_Barge_Quality
    {
        public long RecordId { get; set; }
        public long Loading_Plan_Id { get; set; }
        public long Detail_Barge_Id { get; set; }
        public decimal TM_plan { get; set; }
        public decimal TM_actual { get; set; }
        public decimal M_plan { get; set; }
        public decimal M_actual { get; set; }
        public decimal ASH_plan { get; set; }
        public decimal ASH_actual { get; set; }
        public decimal TS_plan { get; set; }
        public decimal TS_actual { get; set; }
        public decimal CV_ADB_plan { get; set; }
        public decimal CV_ADB_actual { get; set; }
        public decimal CV_AR_plan { get; set; }
        public decimal CV_AR_actual { get; set; }
    }
}
