//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loading_Actual_Barge_Survey_Condition
    {
        public int RecordId { get; set; }
        public long ActualId { get; set; }
        public int Barge_Survey_Condition_Id { get; set; }
        public string Condition { get; set; }
        public string Remark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual Barge_Survey_Condition Barge_Survey_Condition { get; set; }
        public virtual Loading_Actual Loading_Actual { get; set; }
    }
}
