//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loading_Plan_Detail_Barge
    {
        public long RecordId { get; set; }
        public long Loading_Plan_Id { get; set; }
        public string Tug { get; set; }
        public string Barge { get; set; }
        public string Trip_ID { get; set; }
        public System.DateTime EstimateStartLoading { get; set; }
        public int Quantity { get; set; }
        public string Product { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedOn_Date_Only { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual Loading_Plan Loading_Plan { get; set; }
    }
}
