//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loading_Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loading_Plan()
        {
            this.Loading_Plan_Detail_Barge = new HashSet<Loading_Plan_Detail_Barge>();
        }
    
        public long RecordId { get; set; }
        public int SiteId { get; set; }
        public string Company { get; set; }
        public string Shipment_Type { get; set; }
        public string Buyer { get; set; }
        public string Vessel { get; set; }
        public string Destination { get; set; }
        public string Trip_No { get; set; }
        public string Remark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string CreatedOn_Date_Only { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loading_Plan_Detail_Barge> Loading_Plan_Detail_Barge { get; set; }
        public virtual Site Site { get; set; }
    }
}
