//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortionBlending
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PortionBlending()
        {
            this.PortionBlending_Details = new HashSet<PortionBlending_Details>();
        }
    
        public long RecordId { get; set; }
        public string Company { get; set; }
        public string Product { get; set; }
        public System.DateTime BlendingDate { get; set; }
        public int Shift { get; set; }
        public bool NoHauling { get; set; }
        public string Remark { get; set; }
        public double CV { get; set; }
        public double TS { get; set; }
        public double ASH { get; set; }
        public double IM { get; set; }
        public double TM { get; set; }
        public decimal Ton { get; set; }
        public string Hopper { get; set; }
        public string Tunnel { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public int DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> ROM_ID { get; set; }
        public string ROM_Name { get; set; }
        public Nullable<int> TotalBucket { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortionBlending_Details> PortionBlending_Details { get; set; }
    }
}
