//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder_History_Lab_Consumable
    {
        public long RecordId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> Consumable_Data { get; set; }
        public Nullable<int> Period { get; set; }
    }
}
