//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleDetailLoading
    {
        public int Id { get; set; }
        public int SampleId { get; set; }
        public string LoadingNumber { get; set; }
        public string VesselName { get; set; }
        public string DispatchId { get; set; }
        public string Customer { get; set; }
        public System.DateTime ETA { get; set; }
        public System.DateTime ATA { get; set; }
        public string Contract { get; set; }
        public string Product { get; set; }
        public int LotNumber { get; set; }
        public string LotSamples { get; set; }
        public decimal Tonnage { get; set; }
        public System.DateTime SamplingStart { get; set; }
        public System.DateTime SamplingEnd { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<decimal> Size { get; set; }
    
        public virtual Sample Sample { get; set; }
    }
}
