//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleDetailGeneral
    {
        public int Id { get; set; }
        public string GeoPrefix { get; set; }
        public string SampleId { get; set; }
        public int Shift { get; set; }
        public int Sequence { get; set; }
        public System.DateTime DateSampleStart { get; set; }
        public System.DateTime DateSampleEnd { get; set; }
        public System.DateTime Receive { get; set; }
        public decimal Tonnage { get; set; }
        public int Sample_Id { get; set; }
        public string BargeName { get; set; }
        public string Destination { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string TripNumber { get; set; }
    
        public virtual Sample Sample { get; set; }
    }
}
