//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sample()
        {
            this.AnalysisRequestSamples = new HashSet<AnalysisRequestSample>();
            this.SampleDetailGenerals = new HashSet<SampleDetailGeneral>();
            this.SampleDetailLoadings = new HashSet<SampleDetailLoading>();
            this.SampleSchemes = new HashSet<SampleScheme>();
            this.SampleDetailAMDs = new HashSet<SampleDetailAMD>();
        }
    
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public int SiteId { get; set; }
        public string ExternalId { get; set; }
        public System.DateTime DateOfJob { get; set; }
        public int ClientId { get; set; }
        public int ProjectId { get; set; }
        public int RefTypeId { get; set; }
        public string ReceivedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string Stage { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public int JobNumberId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remark { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Thickness { get; set; }
        public Nullable<decimal> ThicknessTo { get; set; }
        public Nullable<decimal> ThicknessFrom { get; set; }
        public string mm_status { get; set; }
        public Nullable<System.DateTime> mm_fetched_at { get; set; }
        public string mm_remark { get; set; }
        public Nullable<int> TunnelId { get; set; }
        public Nullable<int> ValidatedBy { get; set; }
        public Nullable<System.DateTime> ValidatedDate { get; set; }
    
        public virtual AnalysisJob AnalysisJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalysisRequestSample> AnalysisRequestSamples { get; set; }
        public virtual Company Company { get; set; }
        public virtual Site Site { get; set; }
        public virtual Tunnel Tunnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleDetailGeneral> SampleDetailGenerals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleDetailLoading> SampleDetailLoadings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleScheme> SampleSchemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleDetailAMD> SampleDetailAMDs { get; set; }
    }
}
