//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamplingRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SamplingRequest()
        {
            this.SamplingRequest_Lab = new HashSet<SamplingRequest_Lab>();
            this.SamplingRequest_ROM = new HashSet<SamplingRequest_ROM>();
            this.SamplingRequest_SEAM = new HashSet<SamplingRequest_SEAM>();
        }
    
        public long SamplingRequestId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Company { get; set; }
        public string SamplingType { get; set; }
        public string HAC_Text { get; set; }
        public string Tonnage { get; set; }
        public string PICArea { get; set; }
        public string Remark { get; set; }
        public bool CV { get; set; }
        public bool TS { get; set; }
        public bool TM { get; set; }
        public bool PROX { get; set; }
        public bool RD { get; set; }
        public bool SIZE { get; set; }
        public bool FLOW { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public int DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual Company Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SamplingRequest_Lab> SamplingRequest_Lab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SamplingRequest_ROM> SamplingRequest_ROM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SamplingRequest_SEAM> SamplingRequest_SEAM { get; set; }
    }
}
