//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORARY_Barge_Quality_Plan
    {
        public long RecordId { get; set; }
        public long Header { get; set; }
        public string Status { get; set; }
        public string Barge_Ton_plan { get; set; }
        public string Barge_Ton_actual { get; set; }
        public string TM_plan { get; set; }
        public string TM_actual { get; set; }
        public string M_plan { get; set; }
        public string M_actual { get; set; }
        public string ASH_plan { get; set; }
        public string ASH_actual { get; set; }
        public string TS_plan { get; set; }
        public string TS_actual { get; set; }
        public string CV_ADB_plan { get; set; }
        public string CV_ADB_actual { get; set; }
        public string CV_AR_plan { get; set; }
        public string CV_AR_actual { get; set; }
        public string Product { get; set; }
        public string TugName { get; set; }
        public string BargeName { get; set; }
        public bool Barge_Ton_plan_isvalid { get; set; }
        public bool Barge_Ton_actual_isvalid { get; set; }
        public bool TM_plan_isvalid { get; set; }
        public bool TM_actual_isvalid { get; set; }
        public bool M_plan_isvalid { get; set; }
        public bool M_actual_isvalid { get; set; }
        public bool ASH_plan_isvalid { get; set; }
        public bool ASH_actual_isvalid { get; set; }
        public bool TS_plan_isvalid { get; set; }
        public bool TS_actual_isvalid { get; set; }
        public bool CV_ADB_plan_isvalid { get; set; }
        public bool CV_ADB_actual_isvalid { get; set; }
        public bool CV_AR_plan_isvalid { get; set; }
        public bool CV_AR_actual_isvalid { get; set; }
        public bool Product_isvalid { get; set; }
        public bool TugName_isvalid { get; set; }
        public bool BargeName_isvalid { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedOn_Date_Only { get; set; }
    
        public virtual TEMPORARY_Barge_Quality_Plan_Header TEMPORARY_Barge_Quality_Plan_Header { get; set; }
    }
}
