//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORARY_Barge_Line_Up
    {
        public long RecordId { get; set; }
        public long File_Physical { get; set; }
        public int Site { get; set; }
        public string Sheet { get; set; }
        public string Status { get; set; }
        public string EstimateStartLoading { get; set; }
        public string Port_of_Loading { get; set; }
        public string VesselName { get; set; }
        public string TripID { get; set; }
        public string TugBoat { get; set; }
        public string Barge { get; set; }
        public string Product { get; set; }
        public string Capacity { get; set; }
        public string FinalDestinantion { get; set; }
        public string Remark { get; set; }
        public bool EstimateStartLoading_isvalid { get; set; }
        public bool Port_of_Loading_isvalid { get; set; }
        public bool VesselName_isvalid { get; set; }
        public bool TripID_isvalid { get; set; }
        public bool TugBoat_isvalid { get; set; }
        public bool Barge_isvalid { get; set; }
        public bool Product_isvalid { get; set; }
        public bool Capacity_isvalid { get; set; }
        public bool FinalDestinantion_isvalid { get; set; }
        public bool Remark_isvalid { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedOn_Date_Only { get; set; }
    }
}
