//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORARY_Barge_Quality_Plan_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEMPORARY_Barge_Quality_Plan_Header()
        {
            this.TEMPORARY_Barge_Quality_Plan = new HashSet<TEMPORARY_Barge_Quality_Plan>();
        }
    
        public long RecordId { get; set; }
        public long File_Physical { get; set; }
        public int Site { get; set; }
        public string Sheet { get; set; }
        public string TripNo { get; set; }
        public string Vessel { get; set; }
        public string Buyer { get; set; }
        public string Laycan_From { get; set; }
        public string Laycan_To { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedOn_Date_Only { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPORARY_Barge_Quality_Plan> TEMPORARY_Barge_Quality_Plan { get; set; }
        public virtual TEMPORARY_File TEMPORARY_File { get; set; }
    }
}
