//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORARY_CRUSHING_PLANT
    {
        public long RecordId { get; set; }
        public long Header { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Date_Production { get; set; }
        public string Shift_Work { get; set; }
        public string Tonnage { get; set; }
        public string Sample_ID { get; set; }
        public string TM { get; set; }
        public string M { get; set; }
        public string ASH_adb { get; set; }
        public decimal ASH_arb { get; set; }
        public string VM_adb { get; set; }
        public decimal VM_arb { get; set; }
        public decimal FC_adb { get; set; }
        public decimal FC_arb { get; set; }
        public string TS_adb { get; set; }
        public decimal TS_arb { get; set; }
        public string CV_adb { get; set; }
        public decimal CV_db { get; set; }
        public decimal CV_arb { get; set; }
        public decimal CV_daf { get; set; }
        public decimal CV_ad_15 { get; set; }
        public decimal CV_ad_16 { get; set; }
        public decimal CV_ad_17 { get; set; }
        public string Remark { get; set; }
        public string CV_Plan { get; set; }
        public string TM_Plan { get; set; }
        public string ASH_Plan { get; set; }
        public string TS_Plan { get; set; }
        public bool Date_Production_isvalid { get; set; }
        public bool Shift_Work_isvalid { get; set; }
        public bool Tonnage_isvalid { get; set; }
        public bool Sample_ID_isvalid { get; set; }
        public bool TM_isvalid { get; set; }
        public bool M_isvalid { get; set; }
        public bool ASH_adb_isvalid { get; set; }
        public bool ASH_arb_isvalid { get; set; }
        public bool VM_adb_isvalid { get; set; }
        public bool VM_arb_isvalid { get; set; }
        public bool FC_adb_isvalid { get; set; }
        public bool FC_arb_isvalid { get; set; }
        public bool TS_adb_isvalid { get; set; }
        public bool TS_arb_isvalid { get; set; }
        public bool CV_adb_isvalid { get; set; }
        public bool CV_db_isvalid { get; set; }
        public bool CV_arb_isvalid { get; set; }
        public bool CV_daf_isvalid { get; set; }
        public bool CV_ad_15_isvalid { get; set; }
        public bool CV_ad_16_isvalid { get; set; }
        public bool CV_ad_17_isvalid { get; set; }
        public bool Remark_isvalid { get; set; }
        public bool CV_Plan_isvalid { get; set; }
        public bool TM_Plan_isvalid { get; set; }
        public bool ASH_Plan_isvalid { get; set; }
        public bool TS_Plan_isvalid { get; set; }
        public string Company { get; set; }
        public string CreatedOn_Date_Only { get; set; }
        public int CreatedOn_Year_Only { get; set; }
        public string Sheet { get; set; }
    
        public virtual TEMPORARY_CRUSHING_PLANT_Header TEMPORARY_CRUSHING_PLANT_Header { get; set; }
    }
}
