//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORARY_SampleDetail
    {
        public long RecordId { get; set; }
        public long File_Physical { get; set; }
        public string Status { get; set; }
        public string Sheet { get; set; }
        public string SAMPLE { get; set; }
        public string GEOLOGIST { get; set; }
        public string SEAM { get; set; }
        public string SAMPLE_TYPE { get; set; }
        public string DEPTH_FROM { get; set; }
        public string DEPTH_TO { get; set; }
        public string Total_Moisture { get; set; }
        public string Proximate_analysis { get; set; }
        public string Sulfur_content { get; set; }
        public string Calorific_value { get; set; }
        public string Relative_density { get; set; }
        public string CSN { get; set; }
        public string Ash_analysis { get; set; }
        public string HGI { get; set; }
        public string Ultimate_analysis { get; set; }
        public string Chlorine { get; set; }
        public string Phosphorous { get; set; }
        public string Fluorine { get; set; }
        public string Lead_ { get; set; }
        public string Zinc { get; set; }
        public string Form_of_Sulphur { get; set; }
        public string Ash_fusions_temperature { get; set; }
        public string TraceElement { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool SAMPLE_isvalid { get; set; }
    }
}
