//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORARY_File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEMPORARY_File()
        {
            this.TEMPORARY_BARGE_LOADING_Header = new HashSet<TEMPORARY_BARGE_LOADING_Header>();
            this.TEMPORARY_Barge_Quality_Plan_Header = new HashSet<TEMPORARY_Barge_Quality_Plan_Header>();
            this.TEMPORARY_CRUSHING_PLANT_Header = new HashSet<TEMPORARY_CRUSHING_PLANT_Header>();
            this.TEMPORARY_Geology_Explorasi_Header = new HashSet<TEMPORARY_Geology_Explorasi_Header>();
            this.TEMPORARY_Geology_Pit_Monitoring_Header = new HashSet<TEMPORARY_Geology_Pit_Monitoring_Header>();
            this.TEMPORARY_HAC_Header = new HashSet<TEMPORARY_HAC_Header>();
            this.TEMPORARY_Sampling_ROM_Header = new HashSet<TEMPORARY_Sampling_ROM_Header>();
            this.TEMPORARY_VLU = new HashSet<TEMPORARY_VLU>();
        }
    
        public long RecordId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string FileName { get; set; }
        public string Link { get; set; }
        public string FileType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPORARY_BARGE_LOADING_Header> TEMPORARY_BARGE_LOADING_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPORARY_Barge_Quality_Plan_Header> TEMPORARY_Barge_Quality_Plan_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPORARY_CRUSHING_PLANT_Header> TEMPORARY_CRUSHING_PLANT_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPORARY_Geology_Explorasi_Header> TEMPORARY_Geology_Explorasi_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPORARY_Geology_Pit_Monitoring_Header> TEMPORARY_Geology_Pit_Monitoring_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPORARY_HAC_Header> TEMPORARY_HAC_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPORARY_Sampling_ROM_Header> TEMPORARY_Sampling_ROM_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPORARY_VLU> TEMPORARY_VLU { get; set; }
    }
}
