//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORARY_VLU
    {
        public long RecordId { get; set; }
        public long File_Physical { get; set; }
        public int Site { get; set; }
        public string Sheet { get; set; }
        public string Status_Upload { get; set; }
        public string Month { get; set; }
        public string Shipper { get; set; }
        public string NO { get; set; }
        public string VESSEL { get; set; }
        public string LAYCAN_From { get; set; }
        public string LAYCAN_To { get; set; }
        public string DESTINATION { get; set; }
        public string BUYER { get; set; }
        public string ETA { get; set; }
        public string ATA { get; set; }
        public string Commenced_Loading { get; set; }
        public string Completed_Loading { get; set; }
        public string PORT { get; set; }
        public string DEM { get; set; }
        public string STATUS { get; set; }
        public bool Month_isvalid { get; set; }
        public bool Shipper_isvalid { get; set; }
        public bool NO_isvalid { get; set; }
        public bool VESSEL_isvalid { get; set; }
        public bool LAYCAN_isvalid { get; set; }
        public bool LAYCAN_2_isvalid { get; set; }
        public bool DESTINATION_isvalid { get; set; }
        public bool BUYER_isvalid { get; set; }
        public bool ETA_isvalid { get; set; }
        public bool ATA_isvalid { get; set; }
        public bool Commenced_Loading_isvalid { get; set; }
        public bool Completed_Loading_isvalid { get; set; }
        public bool PORT_isvalid { get; set; }
        public bool DEM_isvalid { get; set; }
        public bool STATUS_isvalid { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedOn_Date_Only { get; set; }
    
        public virtual TEMPORARY_File TEMPORARY_File { get; set; }
    }
}
