//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TunnelHistory
    {
        public int RecordId { get; set; }
        public int TunnelId { get; set; }
        public string CompanyCode { get; set; }
        public string Name { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public bool IsActive { get; set; }
        public int ProductId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> StockMovementTunnelId { get; set; }
        public Nullable<decimal> StockMovementTonnage { get; set; }
    
        public virtual Tunnel Tunnel { get; set; }
        public virtual Tunnel Tunnel1 { get; set; }
    }
}
