//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tunnel_Actual_History
    {
        public long RecordId_ { get; set; }
        public System.DateTime CreatedOn_ { get; set; }
        public long HaulingRequest_Reference { get; set; }
        public int TunnelId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public System.DateTime Time { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string Changed_Tunnel { get; set; }
        public Nullable<long> Tunnel_Actual_Id { get; set; }
    }
}
