//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_Geology_Pit_Monitoring
    {
        public long RecordId { get; set; }
        public long TEMPORARY { get; set; }
        public long Header { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string Sample_ID { get; set; }
        public string SampleType { get; set; }
        public string Lab_ID { get; set; }
        public decimal Mass_Spl { get; set; }
        public decimal TM { get; set; }
        public decimal M { get; set; }
        public decimal VM { get; set; }
        public decimal Ash { get; set; }
        public decimal FC { get; set; }
        public decimal TS { get; set; }
        public decimal Cal_ad { get; set; }
        public decimal Cal_db { get; set; }
        public decimal Cal_ar { get; set; }
        public decimal Cal_daf { get; set; }
        public decimal RD { get; set; }
        public string Company { get; set; }
        public string Sheet { get; set; }
        public string CreatedOn_Date_Only { get; set; }
        public int CreatedOn_Year_Only { get; set; }
        public string LECO_Stamp { get; set; }
        public Nullable<decimal> Na2O { get; set; }
        public Nullable<decimal> CaO { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateAnalysis { get; set; }
        public Nullable<decimal> ThicknessFrom { get; set; }
        public Nullable<decimal> ThicknessTo { get; set; }
    }
}
