//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_LECO_CV
    {
        public int RecordId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string NAME { get; set; }
        public string HYDROGEN { get; set; }
        public string OPERATOR { get; set; }
        public string DISCRIPTION { get; set; }
        public string METHOD { get; set; }
        public string MASS_1_gram { get; set; }
        public string CV { get; set; }
        public string FUSE_LENGTH { get; set; }
        public string ANALYSIS_DATE { get; set; }
        public string VESSEL { get; set; }
    }
}
