//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_LECO_TGA
    {
        public int RecordId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string NAME { get; set; }
        public string MOISTURE { get; set; }
        public string VOLATILE { get; set; }
        public string ASH { get; set; }
        public string INITIAL_MASS { get; set; }
        public string CRUCIBLE_MASS { get; set; }
        public string BATCH { get; set; }
        public string LOCATION { get; set; }
        public string METHOD { get; set; }
        public string ANALYSIS_DATE { get; set; }
        public string MAISTURE_MASS { get; set; }
        public string VOLATILE_MASS { get; set; }
        public string ASH_MASS { get; set; }
        public string FIXWD_CARBON { get; set; }
        public string VOLATILE_DRY { get; set; }
        public string ASH_DRY { get; set; }
        public string FIXWD_CARBON_DRY { get; set; }
    }
}
