//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_Sampling_ROM
    {
        public long RecordId { get; set; }
        public long TEMPORARY { get; set; }
        public long Header { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string Date_Request { get; set; }
        public string Date_Sampling { get; set; }
        public string Day_work { get; set; }
        public string LOT { get; set; }
        public string Lab_ID { get; set; }
        public decimal TM { get; set; }
        public decimal M { get; set; }
        public decimal ASH { get; set; }
        public decimal TS { get; set; }
        public int CV { get; set; }
        public string Remark { get; set; }
        public string Seam { get; set; }
        public string Company { get; set; }
        public string Sheet { get; set; }
        public string CreatedOn_Date_Only { get; set; }
        public int CreatedOn_Year_Only { get; set; }
        public string LECO_Stamp { get; set; }
    }
}
