//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_Barge_Quality_Plan_Header
    {
        public long RecordId { get; set; }
        public long File_Physical { get; set; }
        public long TEMPORARY { get; set; }
        public int Site { get; set; }
        public string Sheet { get; set; }
        public string TripNo { get; set; }
        public string Vessel { get; set; }
        public string Buyer { get; set; }
        public System.DateTime Laycan_From { get; set; }
        public System.DateTime Laycan_To { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedOn_Date_Only { get; set; }
    }
}
