//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_CRUSHING_PLANT
    {
        public long RecordId { get; set; }
        public long TEMPORARY { get; set; }
        public long Header { get; set; }
        public string Sheet { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string Date_Production { get; set; }
        public string Shift_Work { get; set; }
        public decimal Tonnage { get; set; }
        public string Sample_ID { get; set; }
        public decimal TM { get; set; }
        public decimal M { get; set; }
        public decimal ASH_adb { get; set; }
        public decimal ASH_arb { get; set; }
        public decimal VM_adb { get; set; }
        public decimal VM_arb { get; set; }
        public decimal FC_adb { get; set; }
        public decimal FC_arb { get; set; }
        public decimal TS_adb { get; set; }
        public decimal TS_arb { get; set; }
        public decimal CV_adb { get; set; }
        public decimal CV_db { get; set; }
        public decimal CV_arb { get; set; }
        public decimal CV_daf { get; set; }
        public decimal CV_ad_15 { get; set; }
        public decimal CV_ad_16 { get; set; }
        public decimal CV_ad_17 { get; set; }
        public string Remark { get; set; }
        public string Company { get; set; }
        public decimal CV_Plan { get; set; }
        public decimal TM_Plan { get; set; }
        public decimal ASH_Plan { get; set; }
        public decimal TS_Plan { get; set; }
        public string CreatedOn_Date_Only { get; set; }
        public int CreatedOn_Year_Only { get; set; }
        public string LECO_Stamp { get; set; }
        public Nullable<System.DateTime> SamplingStart { get; set; }
        public Nullable<System.DateTime> SamplingEnd { get; set; }
        public Nullable<System.DateTime> AnalysisStart { get; set; }
        public Nullable<System.DateTime> AnalysisEnd { get; set; }
    }
}
