//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_LECO_TS
    {
        public int RecordId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string NO { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Weight { get; set; }
        public string Sulfur { get; set; }
        public string Analysis_Time { get; set; }
        public string Date { get; set; }
        public string Method { get; set; }
        public string Operator { get; set; }
        public string Low_Sulfur { get; set; }
        public string High_Sulfur { get; set; }
    }
}
