//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_VLU
    {
        public long RecordId { get; set; }
        public long TEMPORARY { get; set; }
        public int Site { get; set; }
        public string Sheet { get; set; }
        public string Month { get; set; }
        public string Shipper { get; set; }
        public string NO { get; set; }
        public string VESSEL { get; set; }
        public System.DateTime LAYCAN_From { get; set; }
        public System.DateTime LAYCAN_To { get; set; }
        public string DESTINATION { get; set; }
        public string BUYER { get; set; }
        public System.DateTime ETA { get; set; }
        public System.DateTime ATA { get; set; }
        public System.DateTime Commenced_Loading { get; set; }
        public System.DateTime Completed_Loading { get; set; }
        public string PORT { get; set; }
        public decimal DEM { get; set; }
        public string STATUS { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedOn_Date_Only { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
