//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_Barge_Quality_Plan
    {
        public long RecordId { get; set; }
        public long TEMPORARY { get; set; }
        public int Site { get; set; }
        public string Sheet { get; set; }
        public long Header { get; set; }
        public decimal Barge_Ton_plan { get; set; }
        public decimal Barge_Ton_actual { get; set; }
        public decimal TM_plan { get; set; }
        public decimal TM_actual { get; set; }
        public decimal M_plan { get; set; }
        public decimal M_actual { get; set; }
        public decimal ASH_plan { get; set; }
        public decimal ASH_actual { get; set; }
        public decimal TS_plan { get; set; }
        public decimal TS_actual { get; set; }
        public decimal CV_ADB_plan { get; set; }
        public decimal CV_ADB_actual { get; set; }
        public decimal CV_AR_plan { get; set; }
        public decimal CV_AR_actual { get; set; }
        public string Product { get; set; }
        public string TugName { get; set; }
        public string BargeName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedOn_Date_Only { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
