//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.ERD.Analysis_Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnalysisRequest()
        {
            this.AnalysisRequest_Detail = new HashSet<AnalysisRequest_Detail>();
            this.AnalysisRequest_Result = new HashSet<AnalysisRequest_Result>();
        }
    
        public long AnalysisRequestId { get; set; }
        public string Company { get; set; }
        public string AnalysisType { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Sender { get; set; }
        public string LetterNo { get; set; }
        public bool TM { get; set; }
        public bool PROX { get; set; }
        public bool TS { get; set; }
        public bool CV { get; set; }
        public bool RD { get; set; }
        public bool CSN { get; set; }
        public bool AA { get; set; }
        public bool HGI { get; set; }
        public bool Ultimate { get; set; }
        public bool Chlorine { get; set; }
        public bool Phosporus { get; set; }
        public bool Fluorine { get; set; }
        public bool Lead { get; set; }
        public bool Zink { get; set; }
        public bool AFT { get; set; }
        public bool TraceElement { get; set; }
        public bool Others { get; set; }
        public string Others_Text { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public int DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string CoverLetter { get; set; }
        public string CoverLetter2 { get; set; }
    
        public virtual Company Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalysisRequest_Detail> AnalysisRequest_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalysisRequest_Result> AnalysisRequest_Result { get; set; }
    }
}
