//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.ERD.Sampling_Request
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<SamplingRequest> SamplingRequests { get; set; }
        public virtual DbSet<SamplingRequest_History> SamplingRequest_History { get; set; }
        public virtual DbSet<SamplingRequest_Lab> SamplingRequest_Lab { get; set; }
        public virtual DbSet<SamplingRequest_ROM> SamplingRequest_ROM { get; set; }
        public virtual DbSet<SamplingRequest_SEAM> SamplingRequest_SEAM { get; set; }
    }
}
