//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.ERD.Sampling_Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamplingRequest_ROM
    {
        public long RecordId { get; set; }
        public long SamplingRequest { get; set; }
        public Nullable<int> ROM_ID { get; set; }
        public string Block { get; set; }
        public string ROM_Name { get; set; }
    
        public virtual SamplingRequest SamplingRequest1 { get; set; }
    }
}
