//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.ERD.BigData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mercy_Source
    {
        public string Company_code { get; set; }
        public string pit { get; set; }
        public string seam { get; set; }
    }
}
