//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.ERD.BigData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mercy_Product> Mercy_Product { get; set; }
        public virtual DbSet<Mercy_quality_outlook> Mercy_quality_outlook { get; set; }
        public virtual DbSet<Mercy_ROM_Info> Mercy_ROM_Info { get; set; }
        public virtual DbSet<Mercy_ROM_Quality> Mercy_ROM_Quality { get; set; }
        public virtual DbSet<Mercy_Source> Mercy_Source { get; set; }
    }
}
