INSERT Config(Name, Value) VALUES ('Notification_Upload_ROM_Sampling_Date_Format', 'dd-MMM-yyyy HH:mm')
INSERT Config(Name, Value) VALUES ('Notification_Upload_ROM_Sampling_General_Email_Subject', 'New {Company} ROM Sampling Lab Result Report on {Uploaded Date: {UploadedDate}}')
INSERT Config(Name, Value) VALUES ('Notification_Upload_ROM_Sampling_General_Email_To_Menu', 'ROM Sampling')
INSERT Config(Name, Value) VALUES ('Notification_Upload_ROM_Sampling_General_Email_To_Access', 'View')
INSERT Config(Name, Value) VALUES ('Notification_Upload_ROM_Sampling_General_Email_Cc_Menu', 'Upload Lab Analysis Request')
INSERT Config(Name, Value) VALUES ('Notification_Upload_ROM_Sampling_General_Email_Cc_Access', 'Edit')
INSERT Config(Name, Value) VALUES ('Notification_Upload_ROM_Sampling_Specific_Email_Subject', 'New {Company} Lab Result of Sampling Request #{ID} on {Uploaded Date: {UploadedDate}}')
INSERT Config(Name, Value) VALUES ('Notification_Upload_ROM_Sampling_Specific_Email_To_Menu', 'ROM Sampling')
INSERT Config(Name, Value) VALUES ('Notification_Upload_ROM_Sampling_Specific_Email_To_Access', 'Add')
INSERT Config(Name, Value) VALUES ('Notification_Upload_ROM_Sampling_Specific_Email_Cc_Menu', 'Upload Lab Analysis Request')
INSERT Config(Name, Value) VALUES ('Notification_Upload_ROM_Sampling_Specific_Email_Cc_Access', 'Edit')
INSERT Config(Name, Value) VALUES ('PRODUCTION', 'no')
INSERT Config(Name, Value) VALUES ('Email_To', 'sudirman@sudirman.web.id')
INSERT Config(Name, Value) VALUES ('FrontEnd_Url', 'https://dfemercy.banpuindo.co.id')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Pit_Monitoring_Date_Format', 'dd-MMM-yyyy HH:mm')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Pit_Monitoring_General_Email_Subject', 'New {Company} Geology Pit Monitoring Lab Result Report on {Uploaded Date: {Uploaded Date: {UploadedDate}}')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Pit_Monitoring_General_Email_To_Menu', 'Geology Pit Monitoring')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Pit_Monitoring_General_Email_To_Access', 'View')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Pit_Monitoring_General_Email_Cc_Menu', 'Upload Lab Analysis Request')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Pit_Monitoring_General_Email_Cc_Access', 'Edit')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Pit_Monitoring_Specific_Email_Subject', 'New {Company} Lab Result of Analysis Request #{ID} on {Uploaded Date: {UploadedDate}}')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Pit_Monitoring_Specific_Email_To_Menu', 'Geology Pit Monitoring')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Pit_Monitoring_Specific_Email_To_Access', 'Add')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Pit_Monitoring_Specific_Email_Cc_Menu', 'Upload Lab Analysis Request')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Pit_Monitoring_Specific_Email_Cc_Access', 'Edit')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Exploration_Date_Format', 'dd-MMM-yyyy HH:mm')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Exploration_General_Email_Subject', 'New {Company} Geology Exploration Lab Result Report on {Uploaded Date: {UploadedDate}}')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Exploration_General_Email_To_Menu', 'Geology Exploration')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Exploration_General_Email_To_Access', 'View')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Exploration_General_Email_Cc_Menu', 'Upload Lab Analysis Request')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Exploration_General_Email_Cc_Access', 'Edit')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Exploration_Specific_Email_Subject', 'New {Company} Lab Result of Analysis Request #{ID} on {Uploaded Date: {UploadedDate}}')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Exploration_Specific_Email_To_Menu', 'Geology Pit Monitoring')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Exploration_Specific_Email_To_Access', 'Add')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Exploration_Specific_Email_Cc_Menu', 'Upload Lab Analysis Request')
INSERT Config(Name, Value) VALUES ('Notification_Upload_Geology_Exploration_Specific_Email_Cc_Access', 'Edit')
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Crushing_Date_Format', 'dd-MMM-yyyy HH:mm')
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Crushing_Subject', 'New {Company} FC Crushing Lab Result Report on {Uploaded Date: {UploadedDate}}')
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Crushing_To_Menu', 'Crushing Plant')
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Crushing_To_Access', 'View')
GO
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Crushing_Cc_Menu', 'Upload Lab Analysis Request')
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Crushing_Cc_Access', 'Edit')
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Barging_Date_Format', 'dd-MMM-yyyy HH:mm')
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Barging_Subject', 'New {Company} FC Barging Lab Result Report on {Uploaded Date: {UploadedDate}}')
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Barging_To_Menu', 'Barge Loading')
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Barging_To_Access', 'View')
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Barging_Cc_Menu', 'Upload Lab Analysis Request')
INSERT Config(Name, Value) VALUES ('Notification_Upload_FC_Barging_Cc_Access', 'Edit')
INSERT Config(Name, Value) VALUES ('Notification_Sampling_Request_Date_Format', 'dd-MMM-yyyy HH:mm')
INSERT Config(Name, Value) VALUES ('Notification_Sampling_Request_Subject', '[MERCY Local] {Company} - Sampling Request - {SAMPLING_TYPE} - {LOCATION} #{ID}')
INSERT Config(Name, Value) VALUES ('Notification_Sampling_Request_To_Menu', 'Sampling Request')
INSERT Config(Name, Value) VALUES ('Notification_Sampling_Request_To_Access', 'Add')
INSERT Config(Name, Value) VALUES ('Notification_Sampling_Request_Cc_Menu', 'Sampling Request')
INSERT Config(Name, Value) VALUES ('Notification_Sampling_Request_Cc_Access', 'Edit')
INSERT Config(Name, Value) VALUES ('Notification_Analysis_Request_Date_Format', 'dd-MMM-yyyy HH:mm')
INSERT Config(Name, Value) VALUES ('Notification_Analysis_Request_Subject', '[MERCY] {Company} - Analysis Request - {ANALYSIS_TYPE} - {LETTER_NO} #{ID}')
INSERT Config(Name, Value) VALUES ('Notification_Analysis_Request_To_Menu', 'Analysis Request')
INSERT Config(Name, Value) VALUES ('Notification_Analysis_Request_To_Access', 'Add')
INSERT Config(Name, Value) VALUES ('Notification_Analysis_Request_Cc_Menu', 'Analysis Request')
INSERT Config(Name, Value) VALUES ('Notification_Analysis_Request_Cc_Access', 'Edit')
GO