//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework_MineMarket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MERCY_MineMarket_Ctx : DbContext
    {
        public MERCY_MineMarket_Ctx()
            : base("name=MERCY_MineMarket_Ctx")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_MM_MERCY_BARGE> VW_MM_MERCY_BARGE { get; set; }
        public virtual DbSet<VW_MM_MERCY_VESSEL> VW_MM_MERCY_VESSEL { get; set; }
        public virtual DbSet<VW_MM_MERCY_STOCKPILE> VW_MM_MERCY_STOCKPILE { get; set; }
    }
}
