//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework_MineMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MM_MERCY_STOCKPILE
    {
        public int STOCKPILEID { get; set; }
        public string ALIAS1 { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public Nullable<System.DateTime> OPENDATE { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
    }
}
