//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework_MineMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MM_MERCY_BARGE
    {
        public string COMPANYCODE { get; set; }
        public string SERVICE_TRIP { get; set; }
        public string BARGENAME { get; set; }
        public Nullable<System.DateTime> START_ARRIVAL_DATE { get; set; }
        public Nullable<System.DateTime> END_ACTUAL_DATE { get; set; }
        public string PRODUCTNAME { get; set; }
        public double TON_ACTUAL { get; set; }
    }
}
