//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.ERD.Blending_Hauling
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaulingRequest_Detail_PortionBlending
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HaulingRequest_Detail_PortionBlending()
        {
            this.Tunnel_Actual = new HashSet<Tunnel_Actual>();
        }
    
        public long RecordIdx { get; set; }
        public long HaulingRequest { get; set; }
        public long RecordId_Snapshot { get; set; }
        public string Company { get; set; }
        public string Product { get; set; }
        public System.DateTime BlendingDate { get; set; }
        public int Shift { get; set; }
        public bool NoHauling { get; set; }
        public string Remark { get; set; }
        public double CV { get; set; }
        public double TS { get; set; }
        public double ASH { get; set; }
        public double IM { get; set; }
        public double TM { get; set; }
        public decimal Ton { get; set; }
        public string Hopper { get; set; }
        public string Tunnel { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public int DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual HaulingRequest HaulingRequest1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tunnel_Actual> Tunnel_Actual { get; set; }
    }
}
