//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.ERD.Blending_Hauling
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<HaulingRequest> HaulingRequests { get; set; }
        public virtual DbSet<HaulingRequest_Detail> HaulingRequest_Detail { get; set; }
        public virtual DbSet<HaulingRequest_Detail_PortionBlending> HaulingRequest_Detail_PortionBlending { get; set; }
        public virtual DbSet<HaulingRequest_Detail_PortionBlending_Details> HaulingRequest_Detail_PortionBlending_Details { get; set; }
        public virtual DbSet<HaulingRequest_Detail_ROMTransfer> HaulingRequest_Detail_ROMTransfer { get; set; }
        public virtual DbSet<PortionBlending> PortionBlendings { get; set; }
        public virtual DbSet<PortionBlending_Details> PortionBlending_Details { get; set; }
        public virtual DbSet<ROMTransfer> ROMTransfers { get; set; }
        public virtual DbSet<Tunnel> Tunnels { get; set; }
        public virtual DbSet<Tunnel_Actual> Tunnel_Actual { get; set; }
    }
}
