//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.ERD.Blending_Hauling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROMTransfer
    {
        public long RecordId { get; set; }
        public string Company { get; set; }
        public System.DateTime TransferDate { get; set; }
        public int Shift { get; set; }
        public Nullable<int> Source_ROM_ID { get; set; }
        public string Source_Block { get; set; }
        public string Source_ROM_Name { get; set; }
        public Nullable<int> Destination_ROM_ID { get; set; }
        public string Destination_Block { get; set; }
        public string Destination_ROM_Name { get; set; }
        public string Remark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public int DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}
