//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework_PowerBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCY_ROM_QUALITY_ODS
    {
        public int ROM_ID { get; set; }
        public string COMPANY_CODE { get; set; }
        public Nullable<System.DateTime> PROCESS_DATE { get; set; }
        public string BLOCK { get; set; }
        public string ROM_NAME { get; set; }
        public double TON { get; set; }
        public Nullable<double> CV { get; set; }
        public Nullable<double> TS { get; set; }
        public Nullable<double> ASH { get; set; }
        public Nullable<double> IM { get; set; }
        public Nullable<double> TM { get; set; }
    }
}
