//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework_BigData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mercy_ROM_Quality
    {
        public int ROM_Id { get; set; }
        public string company_code { get; set; }
        public Nullable<System.DateTime> Process_Date { get; set; }
        public string Block { get; set; }
        public string ROM_Name { get; set; }
        public Nullable<double> Ton { get; set; }
        public Nullable<double> CV { get; set; }
        public Nullable<double> TS { get; set; }
        public Nullable<double> ASH { get; set; }
        public Nullable<double> IM { get; set; }
        public Nullable<double> TM { get; set; }
    }
}
