//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework_BigData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mercy_ROM_Info
    {
        public int ROM_id { get; set; }
        public string company_code { get; set; }
        public string Block { get; set; }
        public string ROM_Name { get; set; }
    }
}
