//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.ERD.Permissions
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCompany
    {
        public int UserCompanyId { get; set; }
        public int UserId { get; set; }
        public string CompanyCode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
