//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework_BigDataBEK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MERCY_BigDataBEK_Ctx : DbContext
    {
        public MERCY_BigDataBEK_Ctx()
            : base("name=MERCY_BigDataBEK_Ctx")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MERCY_PRODUCT_NEW> MERCY_PRODUCT_NEW { get; set; }
        public virtual DbSet<MERCY_SOURCE_NEW> MERCY_SOURCE_NEW { get; set; }
        public virtual DbSet<MERCY_QUALITY_OUTLOOK> MERCY_QUALITY_OUTLOOK { get; set; }
        public virtual DbSet<MERCY_ROM_INFO> MERCY_ROM_INFO { get; set; }
        public virtual DbSet<MERCY_ROM_QUALITY> MERCY_ROM_QUALITY { get; set; }
    }
}
