//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework_BigDataBEK
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCY_ROM_INFO
    {
        public int ID { get; set; }
        public string COMPANYCODE { get; set; }
        public string BLOCK { get; set; }
        public string ROM_NAME { get; set; }
    }
}
