//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework_BigDataBEK
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCY_QUALITY_OUTLOOK
    {
        public int id { get; set; }
        public string Product_name { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<int> Year { get; set; }
        public string months { get; set; }
        public Nullable<double> CV { get; set; }
        public Nullable<double> TS { get; set; }
        public Nullable<double> ash { get; set; }
        public Nullable<double> IM { get; set; }
        public Nullable<double> TM { get; set; }
    }
}
