//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERCY.Data.EntityFramework_BigDataBEK
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCY_PRODUCT_NEW
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> Available_from { get; set; }
        public Nullable<System.DateTime> Available_until { get; set; }
    }
}
