name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch name
      
jobs:
  build:
    name: Build and Push Docker Image
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build -t my-image .
