name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Packages
      run: |
        echo "## Login to GitHub Packages"
        echo ${{ secrets.ACTION_TOKEN }} | gh auth login --with-token
    - name: Build Docker Image
      run: docker build -t ghcr.io/dirgabrajamusti/aguowb:mercy .
    - name: Login
      run: echo ${{ secrets.ACTION_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push Docker Image to GitHub Packages
      run: docker push ghcr.io/dirgabrajamusti/aguowb:mercy